### ISSUE TITLE
companions dont know how to walk through cactus causeing them to constantly grapple

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#19]
https://github.com/nakano15/terraguardians/assets/89364836/16a7a4b4-38b4-4a66-b9d6-129fdee480f9

**Comment by nakano15** [comment]
Fixed.
The reason why that was happening is because in Constant worlds, the Cactus causes damage to player.
The game recognizes as Cactus can inflict damage regardless of world type, but there must be some internal code that checks wether you're in Constant or not, to decide wether or not cactus will inflict damage.
Companions scripts will now better know to identify if it's a cactus, and if the companion should treat it as a dangerous tile or not depending on world type.
