### ISSUE TITLE
post-moonlord zombie guardian fight is insanely unfair

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#38]
pretty much he is spamming his heal attack constantly not only is he able to heal 7k health like its nothing here ive also seen it cause him to heal over 30k health in one hit even with the zenith it feels impossable to take him down not only that but he seems to have crit damage immunity? and i-frames making it even worse
![Capture133](https://github.com/nakano15/terraguardians/assets/89364836/94c768fb-aaff-47d2-93dd-30d015e9298a)

**Comment by nakano15** [comment]
That surely is absurd. I remember that he recovers health based on a percentage of his health. Maybe that will have to change 
Beside, I need will have to check his and Wrath's stats, because seems like balancing is really off.

**Comment by nakano15** [comment]
Oh, sorry. I forgot to mention a workaround for this issue.
Since the Zombie Guardian seems too much into "social contact" in your playthrough, you can 
try to look for him on a new world, since his stats are based on boss kills progression.

Obviously, the fight will be a lot easier, but at least you can try to beat him.

**Comment by nakano15** [comment]
I changed when the Zombie Guardian will recover health based on his health percentage, to only be when failing to talk to him.
Outside of that, he will only gain twice the damage dealt as health.

Next update will bring the fix.
